#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Movie App', '1.0');

$app->add(new Acme\ShowCommand(new GuzzleHttp\Client));

$app->run();